trainer:
  experiment_name: glm-baseline
  train_csv: data/prudential-life-insurance-assessment/train.csv
  test_csv: data/prudential-life-insurance-assessment/test.csv
preprocessing:
  contract_version: 1
  recipe: kan_paper
model:
  name: glm
  params:
    alpha: 1.0
