trainer:
  experiment_name: stage-c-fourierkan-pareto-sparsity-pareto-q0.629-s0.88
  train_csv: /Users/cyrilgabriele/Documents/School/00_Courses/01_DL/03_Project/DeepLearning/data/prudential-life-insurance-assessment/train.csv
  test_csv: /Users/cyrilgabriele/Documents/School/00_Courses/01_DL/03_Project/DeepLearning/data/prudential-life-insurance-assessment/test.csv
  seed: 42
preprocessing:
  contract_version: 1
  recipe: kan_paper
  selected_features_path: null
model:
  name: tabkan-base
  flavor: fourierkan
  depth: 1
  width: 128
  hidden_widths:
  - 128
  degree: null
  use_layernorm: true
  params:
    max_epochs: 100
    grid_size: 5
    lr: 0.0011202234168345851
    weight_decay: 1.0952927106776856e-06
    batch_size: 256
    l1_weight: 1.0
    entropy_weight: 1.0
    sparsity_lambda: 0.0005
tune:
  name: stage-c-fourierkan-pareto-sparsity
  storage: /Users/cyrilgabriele/Documents/School/00_Courses/01_DL/03_Project/DeepLearning/sweeps/stage_c/fourierkan/all_features/stage-c-fourierkan-pareto-sparsity.db
  n_trials: 33
  timeout: null
  directions:
  - maximize
  - maximize
  sampler: grid
  top_k_candidates: 33
  search_space:
    sparsity_lambda:
      type: grid
      low: null
      high: null
      step: null
      choices: null
      values:
      - 0.0
      - 0.0001
      - 0.0005
      - 0.001
      - 0.00123899
      - 0.0015351
      - 0.00190197
      - 0.00235652
      - 0.00291971
      - 0.00361749
      - 0.00448204
      - 0.0055532
      - 0.00688036
      - 0.0085247
      - 0.010562
      - 0.0130862
      - 0.0162137
      - 0.0200887
      - 0.0248897
      - 0.030838
      - 0.038208
      - 0.0473394
      - 0.0586531
      - 0.0726706
      - 0.0900381
      - 0.111556
      - 0.138217
      - 0.17125
      - 0.212177
      - 0.262885
      - 0.325712
      - 0.403554
      - 0.5
