trainer:
  experiment_name: xgb-baseline
  train_csv: data/prudential-life-insurance-assessment/train.csv
  test_csv: data/prudential-life-insurance-assessment/test.csv
  eval_size: 0.15
preprocessing:
  recipe: kan
  missing_threshold: 0.5
  stratify: true
  use_stratified_kfold: true
  kan_n_splits: 5
model:
  name: xgb
  flavor: null
  depth: 1
  width: 1
  degree: null
  params:
    n_estimators: 500
    max_depth: 6
    learning_rate: 0.1
