trainer:
  experiment_name: stage-c-xgb-top20-tune-tuned
  train_csv: /Users/gian1/CODE/HSG/FS26/DeepLearning/DeepLearning/data/prudential-life-insurance-assessment/train.csv
  test_csv: /Users/gian1/CODE/HSG/FS26/DeepLearning/DeepLearning/data/prudential-life-insurance-assessment/test.csv
  seed: 42
preprocessing:
  contract_version: 1
  recipe: kan_paper
  selected_features_path: /Users/gian1/CODE/HSG/FS26/DeepLearning/DeepLearning/configs/experiment_stages/stage_c_explanation_package/feature_lists/xgb_tuned_top20_features.json
model:
  name: xgb
  flavor: null
  depth: null
  width: null
  hidden_widths: null
  degree: null
  use_layernorm: true
  params:
    n_estimators: 700
    max_depth: 6
    min_child_weight: 2.7720325714166245
    learning_rate: 0.015566623578771902
    subsample: 0.7660296265870522
    colsample_bytree: 0.8290342388521728
    reg_alpha: 8.679591476909849
    reg_lambda: 0.47828838237973337
    gamma: 0.6494881149371003
tune:
  name: stage-c-xgb-top20-tune
  storage: /Users/gian1/CODE/HSG/FS26/DeepLearning/DeepLearning/sweeps/stage-c-xgb-top20-tune.db
  n_trials: 50
  timeout: null
  directions: null
  sampler: tpe
  top_k_candidates: 1
  search_space:
    n_estimators:
      type: int
      low: 100.0
      high: 1200.0
      step: 50
      choices: null
      values: null
    max_depth:
      type: int
      low: 3.0
      high: 15.0
      step: null
      choices: null
      values: null
    min_child_weight:
      type: uniform
      low: 1.0
      high: 15.0
      step: null
      choices: null
      values: null
    learning_rate:
      type: log_uniform
      low: 0.001
      high: 0.3
      step: null
      choices: null
      values: null
    subsample:
      type: uniform
      low: 0.5
      high: 1.0
      step: null
      choices: null
      values: null
    colsample_bytree:
      type: uniform
      low: 0.5
      high: 1.0
      step: null
      choices: null
      values: null
    reg_alpha:
      type: log_uniform
      low: 0.0001
      high: 10.0
      step: null
      choices: null
      values: null
    reg_lambda:
      type: log_uniform
      low: 0.0001
      high: 10.0
      step: null
      choices: null
      values: null
    gamma:
      type: log_uniform
      low: 0.001
      high: 10.0
      step: null
      choices: null
      values: null
